@echo off
:: Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
:: See launcher_rust_analyzer.sh for the rationale; this is the .bat
:: equivalent for Windows. Re-run setup to regenerate.

setlocal

set "WORKSPACE=__WORKSPACE_ROOT__"
set "WRAPPER=%WORKSPACE%\bazel-bin\tools\rust_analyzer\rust_analyzer.exe"

if not exist "%WRAPPER%" (
    pushd "%WORKSPACE%"
    bazel build --ui_event_filters=-info,-stderr --noshow_progress @rules_rust//tools/rust_analyzer:rust_analyzer 1>&2
    if errorlevel 1 (
        popd
        exit /b 1
    )
    popd
)

:: Clear inherited Bazel runfiles env so we resolve our own runfiles via
:: argv[0]+`.runfiles`; see launcher_rust_analyzer.sh for the rationale.
set "RUNFILES_DIR="
set "RUNFILES_MANIFEST_FILE="

"%WRAPPER%" %*
exit /b %errorlevel%
