#!/bin/sh
# Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
# Re-run setup to regenerate; don't edit by hand.
#
# See `launcher_rust_analyzer.sh` for the fast-path-direct-exec
# rationale.
#
# Discover is particularly sensitive to going via `bazel run`: its
# stdout is the JSONL discovery protocol rust-analyzer parses, and any
# non-JSON byte fails parsing. Bazel's "Another command holds the
# output base lock" / "Target up-to-date" messages can interleave into
# stdout when invocations contend, breaking discovery completely.
# Direct exec sidesteps the entire class of contamination bugs.

set -e

# Baked at install time; the discover binary's cache module reads it.
# Override at setup time with `setup <ide> --cache-dir <path>`. Default
# is workspace-local `.rules_rust_analyzer/cache/`.
export RULES_RUST_RA_CACHE_DIR="__RULES_RUST_RA_CACHE_DIR__"

WORKSPACE="__WORKSPACE_ROOT__"
WRAPPER="$WORKSPACE/bazel-bin/tools/rust_analyzer/discover_bazel_rust_project"

if [ ! -x "$WRAPPER" ]; then
    cd "$WORKSPACE"
    bazel build \
        --ui_event_filters=-info,-stderr \
        --noshow_progress \
        @rules_rust//tools/rust_analyzer:discover_bazel_rust_project >&2
fi

# rust-analyzer is itself a rules_rust binary and spawns us with its own
# RUNFILES_DIR / RUNFILES_MANIFEST_FILE in the env. If we let those
# inherit, the runfiles library finds rust-analyzer's runfiles tree
# (which lacks the toolchain JSON we need) instead of ours. Unset so
# `Runfiles::create()` falls back to argv[0]+`.runfiles`.
unset RUNFILES_DIR RUNFILES_MANIFEST_FILE

exec "$WRAPPER" "$@"
