#!/bin/sh
# Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
# Re-run setup to regenerate; don't edit by hand.
#
# See `launcher_rust_analyzer.sh` for the fast-path-direct-exec
# rationale.
#
# The flycheck wrapper itself spawns `bazel build` internally to harvest
# rustc JSON diagnostics. That inner build runs against a DEDICATED
# `--output_user_root` so its `--error_format=json` /
# `--rustc_output_diagnostics=true` flags don't thrash the analysis
# cache of the user's primary Bazel server. The path is exported below
# as `$RULES_RUST_RA_OUTPUT_USER_ROOT`; the wrapper reads it.
#
# Default: `${HOME}/.vscode-server/...` if that dir exists, else
# `${HOME}/.vscode/...`. Override with `setup <ide> --output-user-root
# <abs-path>` — required on Windows for any non-trivial workspace
# (Bazel's path-length budget vs. MAX_PATH).

set -e

export RULES_RUST_RA_OUTPUT_USER_ROOT="__RULES_RUST_RA_OUTPUT_USER_ROOT__"

WORKSPACE="__WORKSPACE_ROOT__"
WRAPPER="$WORKSPACE/bazel-bin/tools/rust_analyzer/flycheck"

if [ ! -x "$WRAPPER" ]; then
    cd "$WORKSPACE"
    bazel build \
        --ui_event_filters=-info,-stderr \
        --noshow_progress \
        @rules_rust//tools/rust_analyzer:flycheck >&2
fi

# rust-analyzer is itself a rules_rust binary and spawns us with its own
# RUNFILES_DIR / RUNFILES_MANIFEST_FILE. Clear them so the flycheck
# wrapper resolves its own runfiles tree via argv[0]+`.runfiles`. See
# launcher_discover_bazel_rust_project.sh for the gory details.
unset RUNFILES_DIR RUNFILES_MANIFEST_FILE

exec "$WRAPPER" "$@"
