#!/bin/sh
# Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
# Re-run setup to regenerate; don't edit by hand.
#
# See `launcher_rust_analyzer.sh` for the fast-path-direct-exec
# rationale; same pattern, different target.

set -e

WORKSPACE="__WORKSPACE_ROOT__"
WRAPPER="$WORKSPACE/bazel-bin/tools/rust_analyzer/rust_analyzer_proc_macro_srv"

if [ ! -x "$WRAPPER" ]; then
    cd "$WORKSPACE"
    bazel build \
        --ui_event_filters=-info,-stderr \
        --noshow_progress \
        @rules_rust//tools/rust_analyzer:rust_analyzer_proc_macro_srv >&2
fi

# Proc-macro-srv is spawned by rust-analyzer (a rules_rust binary), so
# inherited RUNFILES_DIR / RUNFILES_MANIFEST_FILE point at the WRONG
# runfiles tree. Clear them; the wrapper finds its own via argv[0].
unset RUNFILES_DIR RUNFILES_MANIFEST_FILE

exec "$WRAPPER" "$@"
