@echo off
:: Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
:: See launcher_rust_analyzer.sh and launcher_discover_bazel_rust_project.sh
:: for the rationale.

setlocal

set "RULES_RUST_RA_CACHE_DIR=__RULES_RUST_RA_CACHE_DIR__"
set "RULES_RUST_RA_LAUNCHER_DIR=__RULES_RUST_RA_LAUNCHER_DIR__"

set "WORKSPACE=__WORKSPACE_ROOT__"
set "WRAPPER=%WORKSPACE%\bazel-bin\tools\rust_analyzer\discover_bazel_rust_project.exe"

if not exist "%WRAPPER%" (
    pushd "%WORKSPACE%"
    bazel build --ui_event_filters=-info,-stderr --noshow_progress @rules_rust//tools/rust_analyzer:discover_bazel_rust_project 1>&2
    if errorlevel 1 (
        popd
        exit /b 1
    )
    popd
)

set "RUNFILES_DIR="
set "RUNFILES_MANIFEST_FILE="

"%WRAPPER%" %*
exit /b %errorlevel%
