#!/bin/sh
# Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
# Re-run setup to regenerate; don't edit by hand.
#
# Fast path: if the wrapper is already built, exec it directly. Direct
# exec is critical here — `bazel run` keeps the bazel client alive as
# the parent of the LSP for the LSP's entire lifetime, holding the
# per-output-base server lock and blocking every concurrent `bazel
# build` / discover / flycheck / rustfmt invocation against the same
# output base. Direct exec releases the lock immediately after the
# initial build.
#
# Slow path: if the wrapper is missing (first run or after `bazel
# clean`), build it synchronously. Bounded to once per clean.

set -e

# Baked at install time so this launcher works regardless of where it
# lives in the tree (`.vscode/.rules_rust_analyzer/`, `.helix/...`, or
# the workspace-root `.rules_rust_analyzer/`).
WORKSPACE="__WORKSPACE_ROOT__"
WRAPPER="$WORKSPACE/bazel-bin/tools/rust_analyzer/rust_analyzer"

if [ ! -x "$WRAPPER" ]; then
    cd "$WORKSPACE"
    bazel build \
        --ui_event_filters=-info,-stderr \
        --noshow_progress \
        @rules_rust//tools/rust_analyzer:rust_analyzer >&2
fi

# Defensive: if the editor itself was launched from a `bazel run` shell,
# the inherited RUNFILES_* env would steer this binary's runfiles lookup
# at the wrong tree. Same fix as the other launchers.
unset RUNFILES_DIR RUNFILES_MANIFEST_FILE

exec "$WRAPPER" "$@"
