#!/bin/sh
# Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
# Re-run setup to regenerate; don't edit by hand.
#
# See `launcher_rust_analyzer.sh` for the fast-path-direct-exec
# rationale; same pattern, different target.

set -e

WORKSPACE="__WORKSPACE_ROOT__"
WRAPPER="$WORKSPACE/bazel-bin/tools/rust_analyzer/rustfmt"

if [ ! -x "$WRAPPER" ]; then
    cd "$WORKSPACE"
    bazel build \
        --ui_event_filters=-info,-stderr \
        --noshow_progress \
        @rules_rust//tools/rust_analyzer:rustfmt >&2
fi

# rust-analyzer (rules_rust binary) spawns us with its own RUNFILES_DIR
# / RUNFILES_MANIFEST_FILE. Clear to force runfiles lookup via argv[0].
unset RUNFILES_DIR RUNFILES_MANIFEST_FILE

exec "$WRAPPER" "$@"
