@echo off
:: Auto-generated by `bazel run @rules_rust//tools/rust_analyzer:setup`.
:: See launcher_rust_analyzer.sh and launcher_flycheck.sh for the
:: rationale (fast-path-direct-exec + dedicated --output_user_root for
:: the flycheck wrapper's inner `bazel build`).

setlocal

set "RULES_RUST_RA_OUTPUT_USER_ROOT=__RULES_RUST_RA_OUTPUT_USER_ROOT__"

set "WORKSPACE=__WORKSPACE_ROOT__"
set "WRAPPER=%WORKSPACE%\bazel-bin\tools\rust_analyzer\flycheck.exe"

if not exist "%WRAPPER%" (
    pushd "%WORKSPACE%"
    bazel build --ui_event_filters=-info,-stderr --noshow_progress @rules_rust//tools/rust_analyzer:flycheck 1>&2
    if errorlevel 1 (
        popd
        exit /b 1
    )
    popd
)

set "RUNFILES_DIR="
set "RUNFILES_MANIFEST_FILE="

"%WRAPPER%" %*
exit /b %errorlevel%
